---
title: "cleaner GJAM"
author: "Sarah Roberts"
date: "3/30/2019"
output: html_document
---

```{r packages, include=FALSE}
library(gjam)
library(tidyr)#data manipulation
library(dplyr) #data manipulation
library(naniar) #replace with NA
```

```{r load data}
#okay we need to start from scratch because some of the bratt stuff was wonky (there were no species names after the letter M)
#first I am going to load the original spring and fall data
#then make in a workable format 

#load data 
fall_catch <- read.csv("~/Documents/ClimateOceanPlanning/Datasets/NEFSC_Bottom_Trawl/22560_FSCSTables_Fall/22560_UNION_FSCS_SVCAT.csv")
fall_x <- read.csv("~/Documents/ClimateOceanPlanning/Datasets/NEFSC_Bottom_Trawl/22560_FSCSTables_Fall/22560_UNION_FSCS_SVSTA.csv")

spring_catch <- read.csv("~/Documents/ClimateOceanPlanning/Datasets/NEFSC_Bottom_Trawl/22561_FSCSTables_spring/22561_UNION_FSCS_SVCAT.csv")
spring_x <- read.csv("~/Documents/ClimateOceanPlanning/Datasets/NEFSC_Bottom_Trawl/22561_FSCSTables_spring/22561_UNION_FSCS_SVSTA.csv")

```

```{r data manip}
#manipulated the catch data to be in tidy format 
fall_catch <- fall_catch %>% 
 group_by_at(vars(-expcatchnum)) %>% # group by everything other than the value column. 
 mutate(row_id=1:n()) %>% ungroup() %>% # build group index
 spread(key=scientific_name, value=expcatchnum)  # spread

fall_catch$id <- as.numeric(as.character(fall_catch$id))

fall_catch_select <- fall_catch %>% 
  select(-catch_comment) %>% 
  mutate_if(is.factor, as.integer) %>% 
  group_by(id) %>% 
  replace(is.na(.), 0) %>%
 summarise_each(funs(max)) 

fall_catch_select <- fall_catch_select %>% 
  select(-status_code, -svspp, -catchsex, -expcatchwt, -row_id)

#joining the tables 
fall_x$id <- as.numeric(as.character(fall_x$id))
fall <- left_join(fall_catch_select, fall_x, by="id")
fall$season <- "fall"

#doing the same for spring 
spring_catch <- spring_catch %>% 
 group_by_at(vars(-expcatchnum)) %>% # group by everything other than the value column. 
 mutate(row_id=1:n()) %>% ungroup() %>% # build group index
 spread(key=scientific_name, value=expcatchnum)  # spread

spring_catch$id <- as.numeric(as.character(spring_catch$id))

spring_catch_select <- spring_catch %>% 
  select(-catch_comment) %>% 
  mutate_if(is.factor, as.integer) %>% 
  group_by(id) %>% 
  replace(is.na(.), 0) %>%
 summarise_each(funs(max)) 

spring_catch_select <- spring_catch_select %>% 
  select(-status_code, -svspp, -catchsex, -expcatchwt, -row_id)

#joining the tables 
spring_x$id <- as.numeric(as.character(spring_x$id))
spring <- left_join(spring_catch_select, spring_x, by="id")
spring$season <- "spring"

#combining spring and fall 


```


```{r setup, include=FALSE}
#This is the data loading chunk 

bioandcatch <- read.csv("~/Documents/ClimateOceanPlanning/Datasets/NEFSC_Bottom_Trawl/clean_neus_all.csv")
bio <- read.csv("~/Documents/ClimateOceanPlanning/Datasets/NEFSC_Bottom_Trawl/clean_neus_orig.csv")
added_vars <- read.csv("~/Documents/ClimateOceanPlanning/Datasets/NEFSC_Bottom_Trawl/clean_neus_added_vars.csv")
added_vars <- added_vars[-16616,]

bio_select <- bio %>% 
 select(haulid, station, stratum, year, season, lat, lon, datetime, depth, stemp, ssalin, btemp, bsalin, cnt, spp) %>% 
 mutate(ssalin = na_if(ssalin, 99.999))

#this command makes it so every species is a column and the values are the count of each species. This is super helpful so I don't have to use vlookup in excel.
bio_select <- bio_select %>%
 separate(haulid, into=c("ID1", "ID2", "ID3")) %>% 
 unite(ID1, ID2, ID3, col="ID", sep="") 

bio_select <- bio_select %>% 
 group_by_at(vars(-cnt)) %>% # group by everything other than the value column. 
 mutate(row_id=1:n()) %>% ungroup() %>% # build group index
 spread(key=spp, value=cnt)  # spread
 
y_bio_select <- bio_select %>% 
 group_by(ID) %>% 
 select(-station, -stratum, -season, -datetime) %>% 
 select(-year, -lat, -lon, -depth, -ssalin, -stemp, -ssalin, -btemp, -bsalin, -row_id) %>% 
 replace(is.na(.), 0) %>% 
 summarise_each(funs(max)) #smooshes everything into the ID column
#up to now we have all of the y data now need to load the xdata by ID and left join so we have the whole thing. need to add a couple of variables to added vars (season etc)

#summarising some of the xdata within the original dataset NOTE_IN HERE I SHOULD SPLIT UP THE DATE_TIME THING TO GET MONTH THEN CAN ADD A COLUMN FOR SEASON
x_bio_select <- bio_select %>% 
 group_by(ID) %>% 
 select(ID, station, stratum, year, lat, lon, depth, ssalin, stemp, ssalin, btemp, bsalin, row_id,
     datetime) %>% 
 separate(datetime, into=c("month", "day", "Year", "Time")) %>% 
 select(ID, station, stratum, month, day, year, lat, lon, depth, ssalin, stemp, ssalin, btemp,
     bsalin) %>% 
 summarise_each(funs(max)) #smooshes everything into the ID column

x <- added_vars %>%
 separate(haulid, into=c("ID1", "ID2", "ID3")) %>% 
 unite(ID1, ID2, ID3, col="ID", sep="") 

#joining the two 
x_y <- x %>% 
 left_join(y_bio_select, x, by="ID")

x_y <- x_y %>%
 left_join(x_bio_select, x_y, by="ID")

xdata <- x_y %>% 
 select(ID, station, stratum, month, day, year, lat, lon, depth, ssalin, stemp, ssalin, btemp,
     bsalin, AMO_unsm_month, AMO_unsm_year, NAO_month, NAO_year, NAO_JFM, SUBREGION2, BATHYMETRY,
     LPI, SLOPE, SBF_GRP, SBFDEPTH, SEDIMENT, SBFDESED)

ydata <- x_y %>% 
 select(-ID, -station, -stratum, -month, -day, -year, -lat, -lon, -depth, -ssalin, -stemp, -ssalin, -btemp, -bsalin, -AMO_unsm_month, -AMO_unsm_year, -NAO_month, -NAO_year, -NAO_JFM, -SUBREGION2, -BATHYMETRY, -LPI, -SLOPE, -SBF_GRP, -SBFDEPTH, -SEDIMENT, -SBFDESED, -'<NA>')

###checkpoint 
#do we have adataset by ID with all of the x and y data as well as a dataset with just x data and just y data? 

bioandcatch_trimmed <- cbind(ydata, xdata)


bioandcatch_trimmed <- as.data.frame(bioandcatch_trimmed)

#bioandcatch_trimmed$GRPSED <- as.factor(as.character(bioandcatch_trimmed$GRPSED))
bioandcatch_trimmed$SBF_GRP <- as.factor(as.character(bioandcatch_trimmed$SBF_GRP))


bioandcatch_trimmed$est_year <- as.factor(bioandcatch_trimmed$year)
bioandcatch_trimmed$AMO_unsm <- as.numeric(as.character(bioandcatch_trimmed$AMO_unsm_month))
bioandcatch_trimmed$avgdepth <- as.numeric(bioandcatch_trimmed$depth)
bioandcatch_trimmed$surfsalin <- as.numeric(bioandcatch_trimmed$ssalin)
bioandcatch_trimmed$bottemp <- as.numeric(bioandcatch_trimmed$btemp)
bioandcatch_trimmed$NAO <- as.numeric(as.character((bioandcatch_trimmed$NAO_month)))

#"ATLANTOPANDALUS.PROPINQVUS","CANCER.PLEBEJUS", "CHACEON.QUINQUEDENS",
#need to fix this because some things are spelled incorrectly etc 
#specnames from Batt 2017
# `Atlantopandalus propinqvus`, `Hippoglossoides platessoides`,`Hippoglossina oblonga`, `Leptoclinus maculatus`, `Lopholatilus chamaeleonticeps`, `Lumpenus lampretaeformis`, `Lycenchelys verrillii`, `Macrorhamphosus scolopax`, 
ydata <- ydata %>% 
   select(`Acipenser oxyrinchus`, `Alosa aestivalis`, `Alosa pseudoharengus`, `Alosa sapidissima`, `Amblyraja radiata`, `Ammodytes dubius`, `Anarhichas lupus`, `Anchoa hepsetus`, `Anchoa mitchilli`, `Antigonia capros`, `Argentina silus`, `Argentina striata`, `Aspidophoroides monopterygius`,`Bairdiella chrysoura`, `Bathynectes longispina`, `Bathypolypus arcticus`, `Brevoortia tyrannus`, `Brosme brosme`, `Cancer borealis`, `Cancer plebejus`, `Carcharhinus plumbeus`, `Centropristis philadelphica`, `Centropristis striata`, `Chaceon quinquedens`, `Chionoecetes opilio`, `Chlorophthalmus agassizi`, `Citharichthys arctifrons`, `Clupea harengus`, `Conger oceanicus`, `Crangon septemspinosa`, `Cryptacanthodes maculatus`, `Cyclopterus lumpus`, `Cynoscion regalis`, `Dasyatis centroura`, `Dasyatis say`, `Decapterus punctatus`, `Dichelopandalus leptocerus`, `Dipturus laevis`, `Enchelyopus cimbrius`, `Etropus microstomus`, `Etrumeus teres(sadina)`, `Foetorepus agassizii`, `Gadus morhua`, `Glyptocephalus cynoglossus`, `Gymnura altavela`, `Helicolenus dactylopterus`, `Hemitripterus americanus`, `Hippoglossus hippoglossus`, `Homarus americanus`, `Illex illecebrosus`, `Lagodon rhomboides`, `Larimus fasciatus`, `Lebbeus polaris`, `Leiostomus xanthurus`, `Lepophidium profundorum`, `Leucoraja erinacea`, `Leucoraja garmani`, `Leucoraja ocellata`, `Limanda ferruginea`, `Limulus polyphemus`, `Liparis atlanticus`, `Lithodes maja`, `Loligo pealeii`, `Lolliguncula brevis`, `Lophius americanus`, `Malacoraja senta`, `Maurolicus weitzmani`, `Melanogrammus aeglefinus`, `Melanostigma atlanticum`, `Menidia menidia`, `Menticirrhus americanus`, `Menticirrhus saxatilis`, `Merluccius albidus`, `Merluccius bilinearis`, `Micropogonias undulatus`, `Monolene sessilicauda`, `Morone saxatilis`, `Mustelus canis`, `Myliobatis freminvillii`, `Myoxocephalus aenaeus`, `Myoxocephalus octodecemspinosus`, `Myxine glutinosa`, `Nemichthys scolopaceus`, `Ophidion marginatum`, `Osmerus mordax`, `Ovalipes ocellatus`, `Ovalipes stephensoni`, `Pandalus borealis`, `Pandalus montagui`, `Paralichthys dentatus`, `Parasudis truculenta`, `Pasiphaea multidentata`, `Peprilus triacanthus`, `Peristedion miniatum`, `Petromyzon marinus`, `Phycis chesteri`, `Placopecten magellanicus`, `Pollachius virens`, `Polymixia lowei`, `Pomatomus saltatrix`, `Pontinus longispinis`, `Pontophilus norvegicus`, `Prionotus alatus`, `Prionotus carolinus`, `Prionotus evolans`, `Pseudopleuronectes americanus`, `Raja eglanteria`, `Scomber scombrus`, `Scophthalmus aquosus`, `Scyliorhinus retifer`, `Sebastes fasciatus`, `Sicyonia brevirostris`, `Squalus acanthias`, `Squatina dumeril`, `Stenotomus chrysops`, `Syacium papillosum`, `Symphurus plagiusa`, `Synagrops bellus`, `Syngnathus fuscus`, `Synodus foetens`, `Synodus poeyi`, `Tautogolabrus adspersus`, `Trachinocephalus myops`, `Trachurus lathami`, `Trichiurus lepturus`, `Triglops murrayi`, `Trinectes maculatus`, `Ulvaria subbifurcata`, `Urophycis chuss`, `Urophycis regia`, `Urophycis tenuis`, `Zenopsis conchifera`, `Zoarces americanus`)


specNames <- c("ACIPENSER.OXYRYNCHUS"`, `"ALOSA.AESTIVALIS", "ALOSA.PSEUDOHARENGUS", "ALOSA.SAPIDISSIMA", "AMBLYRAJA.RADIATA", "AMMODYTES.DUBIUS", "ANARHICHAS.LUPUS", "ANCHOA.HEPSETUS", "ANCHOA.MITCHILLI", "ANTIGONIA.CAPROS", "ARGENTINA.SILUS", "ARGENTINA.STRIATA", "ASPIDOPHOROIDES.MONOPTERYGIUS", "BAIRDIELLA.CHRYSOURA", "BATHYNECTES.LONGISPINA", "BATHYPOLYPUS.ARCTICUS", "BREVOORTIA.TYRANNUS", "BROSME.BROSME", "CANCER.BOREALIS", "CARCHARHINUS.PLUMBEUS", "CENTROPRISTIS.PHILADELPHICA", "CENTROPRISTIS.STRIATA", "CHIONOECETES.OPILIO", "CHLOROPHTHALMUS.AGASSIZI", "CITHARICHTHYS.ARCTIFRONS", "CLUPEA.HARENGUS", "CONGER.OCEANICUS", "CRANGON.SEPTEMSPINOSA", "CRYPTACANTHODES.MACULATUS", "CYCLOPTERUS.LUMPUS", "CYNOSCION.REGALIS", "DASYATIS.CENTROURA", "DASYATIS.SAY", "DECAPTERUS.PUNCTATUS", "DICHELOPANDALUS.LEPTOCERUS", "DIPTURUS.LAEVIS", "ENCHELYOPUS.CIMBRIUS", "ETROPUS.MICROSTOMUS", "ETRUMEUS.TERES", "FOETOREPUS.AGASSIZII", "GADUS.MORHUA", "GLYPTOCEPHALUS.CYNOGLOSSUS", "GYMNURA.ALTAVELA", "HELICOLENUS.DACTYLOPTERUS", "HEMITRIPTERUS.AMERICANUS", "HIPPOGLOSSINA.OBLONGA", "HIPPOGLOSSOIDES.PLATESSOIDES", "HIPPOGLOSSUS.HIPPOGLOSSUS", "HOMARUS.AMERICANUS", "ILLEX.ILLECEBROSUS", "LAGODON.RHOMBOIDES", "LARIMUS.FASCIATUS", "LEBBEUS.POLARIS", "LEIOSTOMUS.XANTHURUS", "LEPOPHIDIUM.PROFUNDORUM", "LEPTOCLINUS.MACULATUS", "LEUCORAJA.ERINACEA", "LEUCORAJA.GARMANI", "LEUCORAJA.OCELLATA", "LIMANDA.FERRUGINEA", "LIMULUS.POLYPHEMUS", "LIPARIS.ATLANTICUS", "LITHODES.MAJA", "LOLIGO.PEALEII", "LOLLIGUNCULA.BREVIS", "LOPHIUS.AMERICANUS", "LOPHOLATILUS.CHAMAELEONTICEPS", "LUMPENUS.LAMPRETAEFORMIS", "LYCENCHELYS.VERRILLII", "MACRORHAMPHOSUS.SCOLOPAX", "MALACORAJA.SENTA", "MAUROLICUS.WEITZMANI", "MELANOGRAMMUS.AEGLEFINUS", "MELANOSTIGMA.ATLANTICUM", "MENIDIA.MENIDIA", "MENTICIRRHUS.AMERICANUS", "MENTICIRRHUS.SAXATILIS", "MERLUCCIUS.ALBIDUS", "MERLUCCIUS.BILINEARIS", "MICROPOGONIAS.UNDULATUS", "MONOLENE.SESSILICAUDA", "MORONE.SAXATILIS", "MUSTELUS.CANIS", "MYLIOBATIS.FREMINVILLII", "MYOXOCEPHALUS.AENAEUS", "MYOXOCEPHALUS.OCTODECEMSPINOSUS", "MYXINE.GLUTINOSA", "NEMICHTHYS.SCOLOPACEUS", "OPHIDION.MARGINATUM", "OSMERUS.MORDAX", "OVALIPES.OCELLATUS", "OVALIPES.STEPHENSONI", "PANDALUS.BOREALIS", "PANDALUS.MONTAGUI", "PARALICHTHYS.DENTATUS", "PARASUDIS.TRUCULENTA", "PASIPHAEA.MULTIDENTATA", "PEPRILUS.TRIACANTHUS", "PERISTEDION.MINIATUM", "PETROMYZON.MARINUS")

specNames <- c("PHYCIS.CHESTERI", "PLACOPECTEN.MAGELLANICUS", "POLLACHIUS.VIRENS", "POLYMIXIA.LOWEI", "POMATOMUS.SALTATRIX", "PONTINUS.LONGISPINIS", "PONTOPHILUS.NORVEGICUS", "PRIONOTUS.ALATUS", "PRIONOTUS.CAROLINUS", "PRIONOTUS.EVOLANS", "PSEUDOPLEURONECTES.AMERICANUS", "RAJA.EGLANTERIA", "SCOMBER.SCOMBRUS", "SCOPHTHALMUS.AQUOSUS", "SCYLIORHINUS.RETIFER", "SEBASTES.FASCIATUS", "SICYONIA.BREVIROSTRIS", "SQUALUS.ACANTHIAS", "SQUATINA.DUMERIL", "STENOTOMUS.CHRYSOPS", "SYACIUM.PAPILLOSUM", "SYMPHURUS.PLAGIUSA", "SYNAGROPS.BELLUS", "SYNGNATHUS.FUSCUS", "SYNODUS.FOETENS", "SYNODUS.POEYI", "TAUTOGOLABRUS.ADSPERSUS", "TRACHINOCEPHALUS.MYOPS", "TRACHURUS.LATHAMI", "TRICHIURUS.LEPTURUS", "TRIGLOPS.MURRATRINECTES.MACULATUS", "ULVARIA.SUBBIFURCATA", "UROPHYCIS.CHUSS", "UROPHYCIS.REGIA", "UROPHYCIS.TENUIS", "ZENOPSIS.CONCHIFERA", "ZOARCES.AMERICANUS")

specNames <- c(spec1, spec2)

xnames <- c("year", "depth", "btemp", "ssalin", "AMO_unsm_month", "NAO_month", "NAO_JFM", "BATHYMETRY", "SBF_GRP", "SEDIMENT")

ydata <- bioandcatch[,specNames]
xdata <- bioandcatch[,xnames]

```

